package main

import (
	"net/http"
)

func main() {
	// URL: http://54.214.56.32:3000/
	http.HandleFunc("/addByte/", addByte)
	http.HandleFunc("/addComment/", addComment)
	http.HandleFunc("/addMessage/", addMessage)
	http.HandleFunc("/addUser/", addUser)
	http.HandleFunc("/blockBuddy/", blockBuddy)
	http.HandleFunc("/channelListener/", channelListener)
	http.HandleFunc("/deleteByte/", deleteByte)
	http.HandleFunc("/deleteComment/", deleteComment)
	http.HandleFunc("/deleteUser/", deleteUser)
	http.HandleFunc("/disableUser/", disableUser)
	http.HandleFunc("/getBlockedBuddies/", getBlockedBuddies)
	http.HandleFunc("/getBuddy/", getBuddy)
	http.HandleFunc("/getByte/", getByte)
	http.HandleFunc("/getByteComments/", getByteComments)
	http.HandleFunc("/getByteLikes/", getByteLikes)
	http.HandleFunc("/getBytes/", getBytes)
	http.HandleFunc("/getChatIsOnline/", getChatIsOnline)
	http.HandleFunc("/getCommentLikes/", getCommentLikes)
	http.HandleFunc("/getComments/", getComments)
	http.HandleFunc("/getConfig/", getConfig)
	http.HandleFunc("/getImage/", getImage)
	http.HandleFunc("/getLikedBytes/", getLikedBytes)
	http.HandleFunc("/getLikedComments/", getLikedComments)
	http.HandleFunc("/getTabBuddies/", getTabBuddies)
	http.HandleFunc("/getTabBytes/", getTabBytes)
	http.HandleFunc("/getUser/", getUser)
	http.HandleFunc("/isDeletedEmail/", isDeletedEmail)
	http.HandleFunc("/likeByte/", likeByte)
	http.HandleFunc("/likeComment/", likeComment)
	http.HandleFunc("/readMessages/", readMessages)
	http.HandleFunc("/reportBuddy/", reportBuddy)
	http.HandleFunc("/requestNewUsername/", requestNewUsername)
	http.HandleFunc("/signIn/", signIn)
	http.HandleFunc("/signOut/", signOut)
	http.HandleFunc("/syncUser/", syncUser)
	http.HandleFunc("/unblockBuddy/", unblockBuddy)
	http.HandleFunc("/unlikeByte/", unlikeByte)
	http.HandleFunc("/unlikeComment/", unlikeComment)
	http.HandleFunc("/updateBadges/", updateBadges)
	http.HandleFunc("/updateFcmToken/", updateFcmToken)
	http.HandleFunc("/updateNotifications/", updateNotifications)
	http.HandleFunc("/updateUser/", updateUser)

	err := http.ListenAndServe(":3000", nil)
	handleError(err)
}
